"""Always-on serial daemon: outer poll loop + per-DAG work-unit runner.

The daemon is the central orchestrator.  It:

1. Polls the repo registry for ready work units (milestoned issues with
   at least one ``agent-ready`` issue, or un-milestoned ``agent-ready``
   issues as N=1 units).
2. Selects **exactly ONE** ready work unit and awaits it to completion
   before selecting the next (B-I3 serial — never spawns concurrent
   ``asyncio.Task`` objects per work unit).
3. For each work unit, runs the per-DAG serial loop:
   - Builds the DAG via ``gh_deps`` + ``dag.build_dag``.
   - Uses ``IssueScheduler`` for topological ordering.
   - Applies crash / unblock recovery via ``recovery.reconstruct``.
   - Dispatches issues one at a time: ``checkout_feature_branch``,
     record cut-point, label transition (``agent-ready`` →
     ``agent-in-progress``), ``await orch._run_worker(issue)``.
   - Applies the §3.5 outcome protocol.
   - CI-gates merges via ``merge.merge_issue_branch``.
4. On work-unit completion: pushes the feature branch and opens a **draft**
   ``feature/<slug> → main`` PR.  The daemon NEVER merges to ``main``.
5. Escalates stalled issues via ``escalation.escalate`` (dual-channel:
   GitHub comment + optional Slack).

Concurrency contract (B-I3):
    All work units are processed with sequential ``await`` calls.  The
    daemon NEVER spawns ``asyncio.Task`` objects for work units or for
    individual issues within a DAG.  This guarantees that the shared
    repo-root HEAD is only ever checked out to one feature branch at a
    time.

Label state machine (C1 — single writer):
    The daemon is the sole label writer during a run.  ``after_run``
    (inside ``_run_worker``) sets terminal labels; the daemon sets and
    clears ``agent-in-progress``.  ``agent-in-progress`` MUST be cleared
    on every terminal branch (success and all park paths — C-I4).
"""

from __future__ import annotations

import asyncio
import json
import logging
import os
import subprocess
from typing import Any

from baton_harness.chain import branches
from baton_harness.chain.dag import build_dag
from baton_harness.chain.escalation import escalate
from baton_harness.chain.gh_deps import (
    fetch_blocked_by,
)
from baton_harness.chain.merge import MergeOutcome, merge_issue_branch
from baton_harness.chain.recovery import reconstruct
from baton_harness.chain.registry import RepoConfig
from baton_harness.chain.scheduler import IssueScheduler
from baton_harness.vendor.symphony.config import WorkflowConfig
from baton_harness.vendor.symphony.orchestrator import Orchestrator
from baton_harness.vendor.symphony.tracker import Issue

_log = logging.getLogger(__name__)

# Default poll configuration for the CI gate (overridable by caller).
_DEFAULT_CI_POLL_INTERVAL: float = 10.0
_DEFAULT_CI_TIMEOUT: float = 1800.0
_DEFAULT_POLL_INTERVAL_S: float = 30.0

# Claude attribution line for GitHub PR bodies (CLAUDE.md § GitHub Comments).
_CLAUDE_ATTRIBUTION = (
    "\n\n🤖 *Generated by Claude Code on behalf of @cbeaulieu-gt*"
)

# ---------------------------------------------------------------------------
# Subprocess helper (the sole I/O seam; patch this in tests)
# ---------------------------------------------------------------------------


def _run(cmd: list[str]) -> subprocess.CompletedProcess[str]:
    """Run an external command and return its completed process.

    Centralises subprocess invocation so tests can patch a single symbol
    (spike finding F8 — hooks must be independently testable).

    Args:
        cmd: Command and arguments to execute (no shell interpolation).

    Returns:
        A ``subprocess.CompletedProcess`` with captured stdout/stderr.
        Callers inspect ``returncode`` themselves.
    """
    return subprocess.run(
        cmd,
        capture_output=True,
        text=True,
        encoding="utf-8",
    )


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------


def _slugify(title: str) -> str:
    """Convert a milestone title to a URL/git-ref safe slug.

    Rules:
    - Lowercase.
    - Spaces and underscores → ``-``.
    - Strip to ``[A-Za-z0-9._/-]``.
    - Leading non-alphanumeric chars are removed.

    Args:
        title: The milestone title.

    Returns:
        A kebab-case slug safe for use as a git ref component.
    """
    import re

    slug = title.lower()
    slug = slug.replace(" ", "-").replace("_", "-")
    # Strip unsafe characters.
    slug = re.sub(r"[^A-Za-z0-9._/-]", "", slug)
    # Strip leading non-alphanumeric.
    slug = re.sub(r"^[^A-Za-z0-9]+", "", slug)
    return slug or "milestone"


def _label_edit(
    owner: str,
    repo: str,
    issue: int,
    *,
    add: list[str] | None = None,
    remove: list[str] | None = None,
) -> None:
    """Edit labels on a GitHub issue.

    Args:
        owner: The GitHub repository owner.
        repo: The repository name.
        issue: The issue number.
        add: Labels to add (optional).
        remove: Labels to remove (optional).
    """
    cmd = ["gh", "issue", "edit", str(issue), "--repo", f"{owner}/{repo}"]
    for lbl in add or []:
        cmd += ["--add-label", lbl]
    for lbl in remove or []:
        cmd += ["--remove-label", lbl]
    proc = _run(cmd)
    if proc.returncode != 0:
        _log.warning(
            "daemon: gh issue edit failed for #%d (exit %d): %s",
            issue,
            proc.returncode,
            proc.stderr,
        )


def _find_issue_pr(
    owner: str,
    repo: str,
    issue: int,
) -> tuple[str | None, str | None]:
    """Find an open PR's head branch and SHA for a given issue number.

    Looks for a PR whose head branch matches ``baton/*-<N>`` pattern
    (mirrors ``tracker.check_pr_exists`` heuristic).

    Args:
        owner: The GitHub repository owner.
        repo: The repository name.
        issue: The issue number to search for.

    Returns:
        A ``(branch_name, head_sha)`` tuple if found, or
        ``(None, None)`` if no matching PR exists.
    """
    proc = _run(
        [
            "gh",
            "pr",
            "list",
            "--repo",
            f"{owner}/{repo}",
            "--state",
            "open",
            "--json",
            "number,headRefName,headRefOid",
            "--limit",
            "100",
        ]
    )
    if proc.returncode != 0:
        _log.warning(
            "daemon: gh pr list failed (exit %d): %s",
            proc.returncode,
            proc.stderr,
        )
        return None, None

    try:
        prs = json.loads(proc.stdout)
    except (json.JSONDecodeError, TypeError):
        return None, None

    suffix = f"-{issue}"
    for pr in prs:
        head = str(pr.get("headRefName", ""))
        if head.startswith("baton/") and head.endswith(suffix):
            sha = str(pr.get("headRefOid", ""))
            return head, sha

    return None, None


def _fetch_issue_labels(
    owner: str,
    repo: str,
    issue: int,
) -> set[str]:
    """Fetch current labels for an issue (lowercase).

    Args:
        owner: The GitHub repository owner.
        repo: The repository name.
        issue: The issue number.

    Returns:
        A set of lowercase label name strings; empty on error.
    """
    proc = _run(
        [
            "gh",
            "issue",
            "view",
            str(issue),
            "--repo",
            f"{owner}/{repo}",
            "--json",
            "labels",
        ]
    )
    if proc.returncode != 0:
        return set()
    try:
        data = json.loads(proc.stdout)
        return {lbl["name"].lower() for lbl in data.get("labels", [])}
    except (json.JSONDecodeError, KeyError, TypeError):
        return set()


def _fetch_issue_obj(
    owner: str,
    repo: str,
    issue_number: int,
) -> Issue | None:
    """Fetch a single issue as an ``Issue`` dataclass.

    Args:
        owner: The GitHub repository owner.
        repo: The repository name.
        issue_number: The issue number.

    Returns:
        An ``Issue`` object or ``None`` on error.
    """
    proc = _run(
        [
            "gh",
            "issue",
            "view",
            str(issue_number),
            "--repo",
            f"{owner}/{repo}",
            "--json",
            "number,title,state,body,url,labels,assignees",
        ]
    )
    if proc.returncode != 0:
        _log.warning(
            "daemon: gh issue view #%d failed (exit %d): %s",
            issue_number,
            proc.returncode,
            proc.stderr,
        )
        return None
    try:
        raw = json.loads(proc.stdout)
        # gh issue view returns a single object (not a list).
        return Issue.from_gh(raw)
    except (json.JSONDecodeError, KeyError, TypeError) as exc:
        _log.warning("daemon: issue #%d parse error: %s", issue_number, exc)
        return None


def _open_draft_pr(
    owner: str,
    repo: str,
    branch_name: str,
    title: str,
    body: str,
) -> None:
    """Open a draft PR from ``branch_name`` → main.

    The daemon NEVER merges to main — this function only creates a draft PR.

    Args:
        owner: The GitHub repository owner.
        repo: The repository name.
        branch_name: The feature branch to open the PR from.
        title: The PR title.
        body: The PR body (including attribution line).
    """
    proc = _run(
        [
            "gh",
            "pr",
            "create",
            "--repo",
            f"{owner}/{repo}",
            "--draft",
            "--base",
            "main",
            "--head",
            branch_name,
            "--title",
            title,
            "--body",
            body,
        ]
    )
    if proc.returncode != 0:
        # "already exists" is OK — the PR already tracks this branch.
        if "already exists" in proc.stderr or "already exists" in proc.stdout:
            _log.info(
                "daemon: draft PR for %r already exists; skipping create",
                branch_name,
            )
        else:
            _log.warning(
                "daemon: gh pr create failed for %r (exit %d): %s",
                branch_name,
                proc.returncode,
                proc.stderr,
            )
    else:
        _log.info("daemon: draft PR opened for %r → main", branch_name)


# ---------------------------------------------------------------------------
# Per-work-unit runner
# ---------------------------------------------------------------------------


async def _run_work_unit(  # noqa: C901 (acceptable complexity)
    config: WorkflowConfig,
    repo_cfg: RepoConfig,
    branch_name: str,
    slug: str,
    membership: frozenset[int],
    *,
    ci_poll_interval: float = _DEFAULT_CI_POLL_INTERVAL,
    ci_timeout: float = _DEFAULT_CI_TIMEOUT,
) -> None:
    """Run one work unit (one DAG) to completion.

    Sequential ``await`` calls only — no concurrent ``asyncio.Task``
    objects (B-I3 serial contract).

    Args:
        config: The loaded ``WorkflowConfig``.
        repo_cfg: The repo registry entry.
        branch_name: The feature branch name (``"feature/<slug>"``).
        slug: The bare slug (without ``"feature/"`` prefix).
        membership: The frozenset of issue numbers in this work unit.
        ci_poll_interval: Seconds between CI polls in the merge gate.
        ci_timeout: Hard ceiling for the CI gate in seconds.
    """
    owner = repo_cfg.owner
    repo = repo_cfg.repo
    repo_root = repo_cfg.project_root

    # --- Step 0: build the DAG and prepare the scheduler. ---
    blocked_by: dict[int, list[int]] = {}
    for m in membership:
        blocked_by[m] = fetch_blocked_by(owner, repo, m)

    dag = build_dag(membership, blocked_by)
    sched = IssueScheduler(dag.graph)
    try:
        sched.prepare()
    except Exception as exc:
        _log.error(
            "daemon: CycleError in work unit %r: %s; skipping", slug, exc
        )
        escalate(
            owner,
            repo,
            next(iter(membership)),
            f"Cyclic dependency detected in work unit '{slug}': {exc}",
            kind="block",
        )
        return

    # --- Step 1: create or resume the feature branch. ---
    branches.create_feature_branch(repo_root, branch_name, exist_ok=True)

    # Determine if we are resuming (branch existed before
    # create_feature_branch).  Recovery is idempotent on a fresh branch.
    recovery_result = reconstruct(
        repo_root, owner, repo, branch_name, membership
    )

    # Seed the scheduler from recovery.
    for n in recovery_result.done:
        if n in dag.graph:
            # Mark done — consume from sorter first by draining get_ready
            # if it hasn't been consumed yet.  The scheduler only allows
            # mark_done on consumed nodes; seed via the parked path is
            # safer for recovery (avoids graphlib contract violation).
            # Instead, add done nodes to the parked set filtered view is
            # wrong — use mark_parked then immediately correct it via
            # the _done set directly (internal).
            # SAFE approach: track done as pre-seeded; the loop skips them.
            # handled in the loop below via `if n in recovery_result.done`
            pass

    # --- Step 2: per-DAG serial loop. ---
    merged_issues: list[int] = []
    parked_reasons: dict[int, str] = {}

    pending: list[int] = []
    seen: set[int] = set()

    # Orchestrator instance (one per work unit).
    state_path = str(repo_root / ".symphony" / "state.json")
    orch = Orchestrator(
        config=config,
        project_root=str(repo_root),
        state_path=state_path,
    )

    while sched.is_active():
        for n in sched.get_ready():
            if n not in seen:
                seen.add(n)
                pending.append(n)

        # Remove parked from pending.
        pending = [n for n in pending if n not in sched.parked]

        if not pending:
            break  # Fully parked or nothing ready.

        n = pending.pop(0)  # Serial: exactly one issue at a time.

        # --- Recovery seeding. ---
        if n in recovery_result.done:
            sched.mark_done(n)
            merged_issues.append(n)
            continue

        if n in recovery_result.parked_seed:
            sched.mark_parked(n)
            parked_reasons[n] = "blocked (recovery)"
            continue

        if n in recovery_result.ci_gate_reentry:
            # Rule 3a: re-enter CI gate without _run_worker.
            issue_branch, pr_head_sha = _find_issue_pr(owner, repo, n)
            if issue_branch is None or pr_head_sha is None:
                _log.warning(
                    "daemon: ci_gate_reentry for #%d but no open PR found;"
                    " parking",
                    n,
                )
                sched.mark_parked(n)
                parked_reasons[n] = "ci_gate_reentry: no open PR"
                escalate(
                    owner,
                    repo,
                    n,
                    f"Issue #{n} needs CI-gate re-entry but has no open PR.",
                    kind="debug",
                )
                continue

            outcome = merge_issue_branch(
                repo_root=repo_root,
                owner=owner,
                repo=repo,
                issue=n,
                pr_head_sha=pr_head_sha,
                issue_branch=issue_branch,
                feature_branch=branch_name,
                poll_interval=ci_poll_interval,
                timeout=ci_timeout,
            )
            if outcome == MergeOutcome.MERGED:
                _label_edit(
                    owner, repo, n, remove=["agent-in-progress", "agent-done"]
                )
                sched.mark_done(n)
                merged_issues.append(n)
            else:
                _label_edit(owner, repo, n, remove=["agent-in-progress"])
                sched.mark_parked(n)
                parked_reasons[n] = f"ci_gate_reentry: {outcome.name}"
                escalate(
                    owner,
                    repo,
                    n,
                    f"Issue #{n} CI-gate re-entry failed: {outcome.name}",
                    kind="debug",
                )
            continue

        # --- Fresh dispatch (or 3b redispatch). ---
        if n in recovery_result.redispatch:
            # Clear orphan agent-in-progress before re-dispatch (C1).
            _label_edit(owner, repo, n, remove=["agent-in-progress"])
            _log.info("daemon: cleared orphan agent-in-progress for #%d", n)

        # Checkout feature branch (HEAD = feature branch, §3.4).
        branches.checkout_feature_branch(repo_root, slug)
        # Record cut-point (§3.7).
        cut_point = branches.record_cut_point(repo_root, slug)

        # Label transition: remove agent-ready, add agent-in-progress (C1).
        _label_edit(
            owner, repo, n, add=["agent-in-progress"], remove=["agent-ready"]
        )

        # Thread cut-point base to hooks via env (VP-1 wiring).
        os.environ["CHAIN_BASE_BRANCH"] = cut_point
        venv_root = os.environ.get("BH_VENV", "")
        if venv_root:
            os.environ["BH_VENV"] = venv_root

        # Fetch the Issue object.
        issue_obj = _fetch_issue_obj(owner, repo, n)
        if issue_obj is None:
            _log.error("daemon: could not fetch issue #%d; parking", n)
            _label_edit(owner, repo, n, remove=["agent-in-progress"])
            sched.mark_parked(n)
            parked_reasons[n] = "issue fetch failed"
            escalate(
                owner,
                repo,
                n,
                f"Issue #{n} could not be fetched; worker not dispatched.",
                kind="debug",
            )
            continue

        # Dispatch the worker.
        try:
            worker_result = await orch._run_worker(issue_obj)
        except Exception as exc:
            _log.error("daemon: _run_worker raised for #%d: %s", n, exc)
            _label_edit(owner, repo, n, remove=["agent-in-progress"])
            sched.mark_parked(n)
            parked_reasons[n] = f"worker exception: {exc}"
            escalate(
                owner,
                repo,
                n,
                f"Issue #{n} worker raised an exception: {exc}",
                kind="debug",
            )
            continue

        # Re-read labels after _run_worker (after_run may have set blocked).
        post_labels = _fetch_issue_labels(owner, repo, n)
        has_blocked = "blocked" in post_labels

        # Apply §3.5 outcome protocol.
        if worker_result == "pr_created" and not has_blocked:
            # CI gate.
            issue_branch, pr_head_sha = _find_issue_pr(owner, repo, n)
            if issue_branch is None or pr_head_sha is None:
                _log.warning(
                    "daemon: pr_created but no open PR found for #%d; parking",
                    n,
                )
                _label_edit(owner, repo, n, remove=["agent-in-progress"])
                sched.mark_parked(n)
                parked_reasons[n] = "pr_created but no PR located"
                escalate(
                    owner,
                    repo,
                    n,
                    f"Issue #{n} returned pr_created but no PR found.",
                    kind="debug",
                )
                continue

            outcome = merge_issue_branch(
                repo_root=repo_root,
                owner=owner,
                repo=repo,
                issue=n,
                pr_head_sha=pr_head_sha,
                issue_branch=issue_branch,
                feature_branch=branch_name,
                poll_interval=ci_poll_interval,
                timeout=ci_timeout,
            )
            if outcome == MergeOutcome.MERGED:
                # merge_issue_branch already added agent-merged + marker.
                _label_edit(
                    owner, repo, n, remove=["agent-in-progress", "agent-done"]
                )
                sched.mark_done(n)
                merged_issues.append(n)
                _log.info("daemon: issue #%d merged into %r", n, branch_name)
            else:
                _label_edit(owner, repo, n, remove=["agent-in-progress"])
                sched.mark_parked(n)
                parked_reasons[n] = f"CI gate: {outcome.name}"
                reason = (
                    "CI check failed"
                    if outcome == MergeOutcome.CI_FAILED
                    else "CI timed out"
                    if outcome == MergeOutcome.CI_TIMEOUT
                    else "merge conflict"
                )
                escalate(
                    owner,
                    repo,
                    n,
                    f"Issue #{n} parked: {reason} ({outcome.name}).",
                    kind="debug",
                )
        else:
            # Park path: blocked or no_pr.
            kind = "block" if has_blocked else "debug"
            reason_text = (
                "blocked label set"
                if has_blocked
                else "no PR created (agent may have failed)"
            )
            _label_edit(owner, repo, n, remove=["agent-in-progress"])
            sched.mark_parked(n)
            parked_reasons[n] = reason_text
            escalate(
                owner,
                repo,
                n,
                f"Issue #{n} parked: {reason_text}.",
                kind=kind,
            )

    # --- Step 3: completion. ---
    # Push the feature branch.
    push_proc = _run(
        ["git", "-C", str(repo_root), "push", "origin", branch_name]
    )
    if push_proc.returncode != 0:
        _log.warning(
            "daemon: git push %r failed (exit %d): %s",
            branch_name,
            push_proc.returncode,
            push_proc.stderr,
        )

    # Build PR body.
    merged_refs = ", ".join(f"#{n}" for n in merged_issues) or "(none)"
    parked_list = (
        "\n".join(f"- #{n}: {reason}" for n, reason in parked_reasons.items())
        or "(none)"
    )
    pr_body = (
        f"## Work unit: {slug}\n\n"
        f"### Issues merged\n\n{merged_refs}\n\n"
        f"### Issues parked (need human attention)\n\n{parked_list}\n"
        f"{_CLAUDE_ATTRIBUTION}"
    )
    pr_title = f"[daemon] {slug}"
    _open_draft_pr(owner, repo, branch_name, pr_title, pr_body)


# ---------------------------------------------------------------------------
# Outer daemon loop
# ---------------------------------------------------------------------------


async def run_daemon(
    config: WorkflowConfig,
    registry: list[RepoConfig],
    *,
    once: bool = False,
    poll_interval_s: float | None = None,
    ci_poll_interval: float = _DEFAULT_CI_POLL_INTERVAL,
    ci_timeout: float = _DEFAULT_CI_TIMEOUT,
) -> None:
    """Run the always-on serial daemon outer loop.

    Polls the registry for ready work units and processes them one at a
    time (B-I3 serial).  Never exits on a block.

    Args:
        config: The loaded ``WorkflowConfig``.
        registry: The list of ``RepoConfig`` entries (one entry in v1).
        once: If ``True``, run exactly one tick then return (for tests
            and the ``--once`` CLI flag).
        poll_interval_s: Seconds to sleep between outer-loop ticks.
            Defaults to ``config.poll_interval_ms / 1000``.
        ci_poll_interval: Seconds between CI polls in the merge gate.
        ci_timeout: Hard ceiling for the CI gate in seconds.
    """
    if poll_interval_s is None:
        poll_interval_s = config.poll_interval_ms / 1000

    _log.info(
        "daemon: starting (poll_interval=%.1fs, once=%s)",
        poll_interval_s,
        once,
    )

    while True:
        for repo_cfg in registry:
            await _poll_and_run(
                config,
                repo_cfg,
                ci_poll_interval=ci_poll_interval,
                ci_timeout=ci_timeout,
            )

        if once:
            break

        await asyncio.sleep(poll_interval_s)

    _log.info("daemon: stopped")


async def _poll_and_run(
    config: WorkflowConfig,
    repo_cfg: RepoConfig,
    *,
    ci_poll_interval: float,
    ci_timeout: float,
) -> None:
    """Poll one repo for a ready work unit and run it if found.

    Args:
        config: The loaded ``WorkflowConfig``.
        repo_cfg: The repo registry entry.
        ci_poll_interval: Seconds between CI polls.
        ci_timeout: Hard CI ceiling in seconds.
    """
    owner = repo_cfg.owner
    repo = repo_cfg.repo

    # Fetch open agent-ready issues.
    proc = _run(
        [
            "gh",
            "issue",
            "list",
            "--repo",
            f"{owner}/{repo}",
            "--label",
            "agent-ready",
            "--state",
            "open",
            "--json",
            "number,title,state,body,url,labels,milestone,assignees",
            "--limit",
            "100",
        ]
    )
    if proc.returncode != 0:
        _log.error(
            "daemon: gh issue list failed (exit %d): %s",
            proc.returncode,
            proc.stderr,
        )
        return

    try:
        issues_raw = json.loads(proc.stdout)
    except (json.JSONDecodeError, TypeError) as exc:
        _log.error("daemon: issue list parse error: %s", exc)
        return

    # Filter out issues that also have "blocked" label.
    ready_issues = [
        i
        for i in issues_raw
        if "blocked"
        not in {lbl["name"].lower() for lbl in i.get("labels", [])}
    ]

    if not ready_issues:
        _log.debug("daemon: no ready issues in %s/%s", owner, repo)
        return

    # Select ONE ready work unit (B-I3 serial).
    # Priority: milestoned first; then un-milestoned by number.
    work_unit = _select_work_unit(ready_issues)
    if work_unit is None:
        return

    branch_name, slug, membership = work_unit

    await _run_work_unit(
        config=config,
        repo_cfg=repo_cfg,
        branch_name=branch_name,
        slug=slug,
        membership=membership,
        ci_poll_interval=ci_poll_interval,
        ci_timeout=ci_timeout,
    )


def _select_work_unit(
    issues: list[dict[str, Any]],
) -> tuple[str, str, frozenset[int]] | None:
    """Select exactly one ready work unit from the list of ready issues.

    A milestoned issue represents a milestone work unit (all members of
    that milestone form the unit).  An un-milestoned issue is its own
    N=1 unit.

    Selection priority: milestone units first (lowest milestone number),
    then un-milestoned by issue number.

    Args:
        issues: List of raw issue dicts from the ``gh issue list`` output.

    Returns:
        A ``(branch_name, slug, membership)`` tuple or ``None`` if no
        work unit can be determined.
    """
    # Prefer milestoned issues first.
    milestoned = [i for i in issues if i.get("milestone")]
    if milestoned:
        # Pick the milestone with the lowest number.
        milestone = min(
            (i["milestone"] for i in milestoned),
            key=lambda m: m.get("number", 0),
        )
        ms_num = milestone["number"]
        ms_slug = _slugify(milestone.get("title", f"milestone-{ms_num}"))
        branch_name = f"feature/{ms_slug}"
        slug = ms_slug
        # Membership: all issues in this milestone that are ready.
        # recovery.reconstruct adds done/parked members back from history.
        members = frozenset(
            i["number"]
            for i in milestoned
            if i.get("milestone", {}).get("number") == milestone["number"]
        )
        return branch_name, slug, members

    # Un-milestoned: pick the lowest issue number.
    un_milestoned = sorted(
        [i for i in issues if not i.get("milestone")],
        key=lambda i: i["number"],
    )
    if un_milestoned:
        n = un_milestoned[0]["number"]
        from baton_harness.chain.branches import feature_branch_name

        branch_name = feature_branch_name(issue=n)
        slug = f"issue-{n}"
        return branch_name, slug, frozenset({n})

    return None
