"""Always-on serial daemon: outer poll loop + per-DAG work-unit runner.

The daemon is the central orchestrator.  It:

1. Polls the repo registry for ready work units (milestoned issues with
   at least one ``agent-ready`` issue, or un-milestoned ``agent-ready``
   issues as N=1 units).
2. Selects **exactly ONE** ready work unit and awaits it to completion
   before selecting the next (B-I3 serial — never spawns concurrent
   ``asyncio.Task`` objects per work unit).
3. For each work unit, runs the per-DAG serial loop:
   - Builds the DAG via ``gh_deps`` + ``dag.build_dag``.
   - Uses ``IssueScheduler`` for topological ordering.
   - Applies crash / unblock recovery via ``recovery.reconstruct``.
   - Dispatches issues one at a time: ``checkout_feature_branch``,
     record cut-point, label transition (``agent-ready`` →
     ``agent-in-progress``), ``await orch._run_worker(issue)``.
   - Applies the §3.5 outcome protocol.
   - CI-gates merges via ``merge.merge_issue_branch``.
4. On work-unit completion: pushes the feature branch and opens a **draft**
   ``feature/<slug> → main`` PR.  The daemon NEVER merges to ``main``.
5. Escalates stalled issues via ``escalation.escalate`` (dual-channel:
   GitHub comment + optional Slack).

Concurrency contract (B-I3):
    All work units are processed with sequential ``await`` calls.  The
    daemon NEVER spawns ``asyncio.Task`` objects for work units or for
    individual issues within a DAG.  This guarantees that the shared
    repo-root HEAD is only ever checked out to one feature branch at a
    time.

Label state machine (C1 — single writer):
    The daemon is the sole label writer during a run.  ``after_run``
    (inside ``_run_worker``) sets terminal labels; the daemon sets and
    clears ``agent-in-progress``.  ``agent-in-progress`` MUST be cleared
    on every terminal branch (success and all park paths — C-I4).
"""

from __future__ import annotations

import asyncio
import json
import logging
import os
import subprocess
import sys
from datetime import datetime, timezone
from typing import Any

from baton_harness.chain import branches
from baton_harness.chain.dag import build_dag
from baton_harness.chain.escalation import alert
from baton_harness.chain.gh_deps import (
    fetch_blocked_by,
)
from baton_harness.chain.merge import MergeOutcome, merge_issue_branch
from baton_harness.chain.obs_config import load_obs_config
from baton_harness.chain.recovery import reconstruct
from baton_harness.chain.registry import RepoConfig
from baton_harness.chain.runlog import RunLog
from baton_harness.chain.scheduler import IssueScheduler
from baton_harness.vendor.symphony.config import WorkflowConfig
from baton_harness.vendor.symphony.orchestrator import Orchestrator
from baton_harness.vendor.symphony.tracker import Issue

_log = logging.getLogger(__name__)

# Default poll configuration for the CI gate (overridable by caller).
_DEFAULT_CI_POLL_INTERVAL: float = 10.0
_DEFAULT_CI_TIMEOUT: float = 1800.0
_DEFAULT_POLL_INTERVAL_S: float = 30.0

# Claude attribution line for GitHub PR bodies (CLAUDE.md § GitHub Comments).
_CLAUDE_ATTRIBUTION = (
    "\n\n🤖 *Generated by Claude Code on behalf of @cbeaulieu-gt*"
)

# ---------------------------------------------------------------------------
# Subprocess helper (the sole I/O seam; patch this in tests)
# ---------------------------------------------------------------------------


def _run(cmd: list[str]) -> subprocess.CompletedProcess[str]:
    """Run an external command and return its completed process.

    Centralises subprocess invocation so tests can patch a single symbol
    (spike finding F8 — hooks must be independently testable).

    Args:
        cmd: Command and arguments to execute (no shell interpolation).

    Returns:
        A ``subprocess.CompletedProcess`` with captured stdout/stderr.
        Callers inspect ``returncode`` themselves.
    """
    return subprocess.run(
        cmd,
        capture_output=True,
        text=True,
        encoding="utf-8",
    )


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------


def _slugify(title: str) -> str:
    """Convert a milestone title to a URL/git-ref safe slug.

    Rules:
    - Lowercase.
    - Spaces and underscores → ``-``.
    - Strip to ``[A-Za-z0-9._/-]``.
    - Leading non-alphanumeric chars are removed.

    Args:
        title: The milestone title.

    Returns:
        A kebab-case slug safe for use as a git ref component.
    """
    import re

    slug = title.lower()
    slug = slug.replace(" ", "-").replace("_", "-")
    # Strip unsafe characters.
    slug = re.sub(r"[^A-Za-z0-9._/-]", "", slug)
    # Strip leading non-alphanumeric.
    slug = re.sub(r"^[^A-Za-z0-9]+", "", slug)
    return slug or "milestone"


def _label_edit(
    owner: str,
    repo: str,
    issue: int,
    *,
    add: list[str] | None = None,
    remove: list[str] | None = None,
) -> None:
    """Edit labels on a GitHub issue.

    Args:
        owner: The GitHub repository owner.
        repo: The repository name.
        issue: The issue number.
        add: Labels to add (optional).
        remove: Labels to remove (optional).
    """
    cmd = ["gh", "issue", "edit", str(issue), "--repo", f"{owner}/{repo}"]
    for lbl in add or []:
        cmd += ["--add-label", lbl]
    for lbl in remove or []:
        cmd += ["--remove-label", lbl]
    proc = _run(cmd)
    if proc.returncode != 0:
        _log.warning(
            "daemon: gh issue edit failed for #%d (exit %d): %s",
            issue,
            proc.returncode,
            proc.stderr,
        )


def _find_issue_pr(
    owner: str,
    repo: str,
    issue: int,
) -> tuple[str | None, str | None]:
    """Find an open PR's head branch and SHA for a given issue number.

    Looks for a PR whose head branch matches ``baton/*-<N>`` pattern
    (mirrors ``tracker.check_pr_exists`` heuristic).

    Args:
        owner: The GitHub repository owner.
        repo: The repository name.
        issue: The issue number to search for.

    Returns:
        A ``(branch_name, head_sha)`` tuple if found, or
        ``(None, None)`` if no matching PR exists.
    """
    proc = _run(
        [
            "gh",
            "pr",
            "list",
            "--repo",
            f"{owner}/{repo}",
            "--state",
            "open",
            "--json",
            "number,headRefName,headRefOid",
            "--limit",
            "100",
        ]
    )
    if proc.returncode != 0:
        _log.warning(
            "daemon: gh pr list failed (exit %d): %s",
            proc.returncode,
            proc.stderr,
        )
        return None, None

    try:
        prs = json.loads(proc.stdout)
    except (json.JSONDecodeError, TypeError):
        return None, None

    suffix = f"-{issue}"
    for pr in prs:
        head = str(pr.get("headRefName", ""))
        if head.startswith("baton/") and head.endswith(suffix):
            sha = str(pr.get("headRefOid", ""))
            return head, sha

    return None, None


def _fetch_issue_labels(
    owner: str,
    repo: str,
    issue: int,
) -> set[str]:
    """Fetch current labels for an issue (lowercase).

    Args:
        owner: The GitHub repository owner.
        repo: The repository name.
        issue: The issue number.

    Returns:
        A set of lowercase label name strings; empty on error.
    """
    proc = _run(
        [
            "gh",
            "issue",
            "view",
            str(issue),
            "--repo",
            f"{owner}/{repo}",
            "--json",
            "labels",
        ]
    )
    if proc.returncode != 0:
        return set()
    try:
        data = json.loads(proc.stdout)
        return {lbl["name"].lower() for lbl in data.get("labels", [])}
    except (json.JSONDecodeError, KeyError, TypeError):
        return set()


def _fetch_issue_obj(
    owner: str,
    repo: str,
    issue_number: int,
) -> Issue | None:
    """Fetch a single issue as an ``Issue`` dataclass.

    Args:
        owner: The GitHub repository owner.
        repo: The repository name.
        issue_number: The issue number.

    Returns:
        An ``Issue`` object or ``None`` on error.
    """
    proc = _run(
        [
            "gh",
            "issue",
            "view",
            str(issue_number),
            "--repo",
            f"{owner}/{repo}",
            "--json",
            "number,title,state,body,url,labels,assignees",
        ]
    )
    if proc.returncode != 0:
        _log.warning(
            "daemon: gh issue view #%d failed (exit %d): %s",
            issue_number,
            proc.returncode,
            proc.stderr,
        )
        return None
    try:
        raw = json.loads(proc.stdout)
        # gh issue view returns a single object (not a list).
        return Issue.from_gh(raw)
    except (json.JSONDecodeError, KeyError, TypeError) as exc:
        _log.warning("daemon: issue #%d parse error: %s", issue_number, exc)
        return None


def _fetch_full_milestone_members(
    owner: str,
    repo: str,
    milestone_number: int,
    milestone_title: str,
) -> frozenset[int]:
    """Fetch all OPEN issues for a milestone — the full DAG membership set.

    Uses ``gh issue list --milestone <title> --state open`` (the CLI
    matches by title string, not by number).  Closed milestone issues are
    intentionally excluded: a closed blocker is a satisfied blocker, so
    its dependents correctly become ready.

    This is distinct from the ``agent-ready`` subset returned by the poll
    query.  The full set is required so that ``build_dag`` sees all
    blocker edges — if a non-ready member A blocks a ready member B and A
    is excluded from membership, the edge A→B is dropped and B is
    incorrectly dispatched before A completes.

    Args:
        owner: The GitHub repository owner.
        repo: The repository name.
        milestone_number: The milestone integer ID (used as fallback only).
        milestone_title: The milestone title string (used for the CLI
            ``--milestone`` filter).

    Returns:
        A ``frozenset`` of all open issue numbers in the milestone.
        Falls back to an empty frozenset on error.
    """
    proc = _run(
        [
            "gh",
            "issue",
            "list",
            "--repo",
            f"{owner}/{repo}",
            "--milestone",
            milestone_title,
            "--state",
            "open",
            "--json",
            "number,title,state,body,url,labels,milestone,assignees",
            "--limit",
            "200",
        ]
    )
    if proc.returncode != 0:
        _log.warning(
            "daemon: gh issue list --milestone %r failed (exit %d): %s; "
            "falling back to agent-ready subset",
            milestone_title,
            proc.returncode,
            proc.stderr,
        )
        return frozenset()
    try:
        issues_raw = json.loads(proc.stdout)
        return frozenset(i["number"] for i in issues_raw)
    except (json.JSONDecodeError, KeyError, TypeError) as exc:
        _log.warning(
            "daemon: milestone member parse error for %r: %s; "
            "falling back to agent-ready subset",
            milestone_title,
            exc,
        )
        return frozenset()


def _open_draft_pr(
    owner: str,
    repo: str,
    branch_name: str,
    title: str,
    body: str,
) -> None:
    """Open a draft PR from ``branch_name`` → main.

    The daemon NEVER merges to main — this function only creates a draft PR.

    Args:
        owner: The GitHub repository owner.
        repo: The repository name.
        branch_name: The feature branch to open the PR from.
        title: The PR title.
        body: The PR body (including attribution line).
    """
    proc = _run(
        [
            "gh",
            "pr",
            "create",
            "--repo",
            f"{owner}/{repo}",
            "--draft",
            "--base",
            "main",
            "--head",
            branch_name,
            "--title",
            title,
            "--body",
            body,
        ]
    )
    if proc.returncode != 0:
        # "already exists" is OK — the PR already tracks this branch.
        if "already exists" in proc.stderr or "already exists" in proc.stdout:
            _log.info(
                "daemon: draft PR for %r already exists; skipping create",
                branch_name,
            )
        else:
            _log.warning(
                "daemon: gh pr create failed for %r (exit %d): %s",
                branch_name,
                proc.returncode,
                proc.stderr,
            )
    else:
        _log.info("daemon: draft PR opened for %r → main", branch_name)


# ---------------------------------------------------------------------------
# Per-work-unit runner
# ---------------------------------------------------------------------------


async def _run_work_unit(  # noqa: C901 (acceptable complexity)
    config: WorkflowConfig,
    repo_cfg: RepoConfig,
    branch_name: str,
    slug: str,
    membership: frozenset[int],
    *,
    agent_ready_issues: frozenset[int] | None = None,
    ci_poll_interval: float = _DEFAULT_CI_POLL_INTERVAL,
    ci_timeout: float = _DEFAULT_CI_TIMEOUT,
    runlog: RunLog | None = None,
) -> None:
    """Run one work unit (one DAG) to completion.

    Sequential ``await`` calls only — no concurrent ``asyncio.Task``
    objects (B-I3 serial contract).

    Args:
        config: The loaded ``WorkflowConfig``.
        repo_cfg: The repo registry entry.
        branch_name: The feature branch name (``"feature/<slug>"``).
        slug: The bare slug (without ``"feature/"`` prefix).
        membership: The full set of open milestone issue numbers (FIX 1).
            For un-milestoned single-issue units this is ``{N}``.
        agent_ready_issues: The subset of ``membership`` that currently
            carry the ``agent-ready`` label.  Only issues in this set are
            dispatched to the worker; others are treated as
            "waiting-for-greenlight" and skipped without escalation.
            Defaults to ``membership`` when ``None`` (backward-compat for
            un-milestoned units where membership IS the ready set).
        ci_poll_interval: Seconds between CI polls in the merge gate.
        ci_timeout: Hard ceiling for the CI gate in seconds.
        runlog: Optional ``RunLog`` handle for best-effort event
            emission.  When ``None``, all emission is a no-op.
    """
    owner = repo_cfg.owner
    repo = repo_cfg.repo
    repo_root = repo_cfg.project_root

    # FIX 1: default agent_ready_issues to membership when caller did not
    # supply it (un-milestoned N=1 unit where membership IS the ready set).
    if agent_ready_issues is None:
        agent_ready_issues = membership

    # --- Step 0: build the DAG and prepare the scheduler. ---
    blocked_by: dict[int, list[int]] = {}
    for m in membership:
        blocked_by[m] = fetch_blocked_by(owner, repo, m)

    dag = build_dag(membership, blocked_by)
    sched = IssueScheduler(dag.graph)
    try:
        sched.prepare()
    except Exception as exc:
        # FIX 4: CycleError is a recoverable escalated condition — warning,
        # not error.
        _log.warning(
            "daemon: CycleError in work unit %r: %s; skipping", slug, exc
        )
        alert(
            owner,
            repo,
            next(iter(membership)),
            f"Cyclic dependency detected in work unit '{slug}': {exc}",
            severity="warn",
            kind="block",
            runlog=runlog,
        )
        return

    # --- Step 1: create or resume the feature branch. ---
    branches.create_feature_branch(repo_root, branch_name, exist_ok=True)

    # Issue #67 / PR #69 (Codex P1): publish the feature branch to origin
    # NOW, before any worker/agent runs.  The agent's WORKFLOW.md uses
    #   gh pr create --base "$BH_FEATURE_BRANCH"
    # which requires the base branch to already exist on the remote.  The
    # completion push at Step 3 below publishes merge commits at unit end,
    # but for a fresh work unit `origin/<branch_name>` does not yet exist
    # when the first _run_worker executes.  An idempotent early push fixes
    # the ordering: re-runs where the branch is already on origin are no-ops
    # (git exits 0 for up-to-date / fast-forwardable pushes).
    early_push = _run(
        ["git", "-C", str(repo_root), "push", "origin", branch_name]
    )
    if early_push.returncode != 0:
        _log.warning(
            "daemon: early git push %r to origin failed (exit %d): %s",
            branch_name,
            early_push.returncode,
            early_push.stderr,
        )

    # Determine if we are resuming (branch existed before
    # create_feature_branch).  Recovery is idempotent on a fresh branch.
    recovery_result = reconstruct(
        repo_root, owner, repo, branch_name, membership
    )

    # --- Step 2: per-DAG serial loop. ---
    merged_issues: list[int] = []
    parked_reasons: dict[int, str] = {}

    pending: list[int] = []
    seen: set[int] = set()

    # Orchestrator instance (one per work unit).
    state_path = str(repo_root / ".symphony" / "state.json")
    orch = Orchestrator(
        config=config,
        project_root=str(repo_root),
        state_path=state_path,
    )

    # FIX 4: set BH_VENV once before the loop.  If it is already set by
    # the launcher, leave it; if unset, derive from the running interpreter
    # so hooks can self-activate the venv.
    if not os.environ.get("BH_VENV"):
        # sys.executable is e.g. /path/to/.venv/Scripts/python.exe;
        # the venv root is one level above the bin/Scripts dir.
        venv_root = str(
            __import__("pathlib").Path(sys.executable).parent.parent
        )
        os.environ["BH_VENV"] = venv_root

    while sched.is_active():
        for n in sched.get_ready():
            if n not in seen:
                seen.add(n)
                pending.append(n)

        # Remove parked from pending.
        pending = [n for n in pending if n not in sched.parked]

        if not pending:
            break  # Fully parked or nothing ready.

        # FIX 1: partition pending into actionable and non-actionable.
        # "Actionable" = recovery-case OR currently carries agent-ready.
        # "Non-actionable" = full milestone member that has NOT been
        # greenlit yet (agent-ready not set by human).  Non-actionable
        # issues are skipped silently — they will be picked up in a
        # future poll tick once the human adds agent-ready.
        recovery_actionable = {
            m
            for m in pending
            if m in recovery_result.done
            or m in recovery_result.parked_seed
            or m in recovery_result.ci_gate_reentry
            or m in recovery_result.redispatch
        }
        dispatch_actionable = {m for m in pending if m in agent_ready_issues}
        actionable = recovery_actionable | dispatch_actionable

        if not actionable:
            # Only un-greenlit milestone members remain in the frontier.
            # Exit the work unit cleanly (open the draft PR below) without
            # escalating.  The outer poll loop will re-trigger this milestone
            # on the next tick once the human labels more issues agent-ready.
            _log.info(
                "daemon: work unit %r: frontier has only un-greenlit members"
                " %s; exiting cleanly to wait for human greenlight",
                slug,
                sorted(pending),
            )
            break

        n = pending.pop(0)  # Serial: exactly one issue at a time.

        # FIX 1: if this issue is non-actionable, skip it (leave it
        # undispatched so the loop can continue processing actionable siblings
        # that were also in the pending list).
        if n not in actionable:
            _log.debug(
                "daemon: #%d not yet agent-ready; skipping this pass", n
            )
            continue

        # --- Recovery seeding. ---
        if n in recovery_result.done:
            sched.mark_done(n)
            merged_issues.append(n)
            continue

        if n in recovery_result.parked_seed:
            sched.mark_parked(n)
            parked_reasons[n] = "blocked (recovery)"
            continue

        if n in recovery_result.ci_gate_reentry:
            # Rule 3a: re-enter CI gate without _run_worker.
            issue_branch, pr_head_sha = _find_issue_pr(owner, repo, n)
            if issue_branch is None or pr_head_sha is None:
                _log.warning(
                    "daemon: ci_gate_reentry for #%d but no open PR found;"
                    " parking",
                    n,
                )
                sched.mark_parked(n)
                parked_reasons[n] = "ci_gate_reentry: no open PR"
                alert(
                    owner,
                    repo,
                    n,
                    f"Issue #{n} needs CI-gate re-entry but has no open PR.",
                    severity="critical",
                    kind="debug",
                    runlog=runlog,
                )
                continue

            # FIX 2: wrap merge_issue_branch in a per-issue try/except so a
            # transient git/gh error parks this issue but does not kill the
            # daemon.
            try:
                outcome = merge_issue_branch(
                    repo_root=repo_root,
                    owner=owner,
                    repo=repo,
                    issue=n,
                    pr_head_sha=pr_head_sha,
                    issue_branch=issue_branch,
                    feature_branch=branch_name,
                    poll_interval=ci_poll_interval,
                    timeout=ci_timeout,
                )
            except Exception as exc:
                _log.error(
                    "daemon: merge_issue_branch raised for #%d (ci_gate"
                    "_reentry): %s; parking",
                    n,
                    exc,
                )
                _label_edit(owner, repo, n, remove=["agent-in-progress"])
                sched.mark_parked(n)
                parked_reasons[n] = f"merge exception (ci_gate): {exc}"
                alert(
                    owner,
                    repo,
                    n,
                    f"Issue #{n} merge failed (ci_gate_reentry): {exc}",
                    severity="warn",
                    kind="debug",
                    runlog=runlog,
                )
                continue

            if outcome == MergeOutcome.MERGED:
                _label_edit(
                    owner, repo, n, remove=["agent-in-progress", "agent-done"]
                )
                sched.mark_done(n)
                merged_issues.append(n)
            else:
                _label_edit(owner, repo, n, remove=["agent-in-progress"])
                sched.mark_parked(n)
                parked_reasons[n] = f"ci_gate_reentry: {outcome.name}"
                alert(
                    owner,
                    repo,
                    n,
                    f"Issue #{n} CI-gate re-entry failed: {outcome.name}",
                    severity="critical",
                    kind="debug",
                    runlog=runlog,
                )
            continue

        # --- Fresh dispatch (or 3b redispatch). ---
        if n in recovery_result.redispatch:
            # Clear orphan agent-in-progress before re-dispatch (C1).
            _label_edit(owner, repo, n, remove=["agent-in-progress"])
            _log.info("daemon: cleared orphan agent-in-progress for #%d", n)

        # Checkout feature branch (HEAD = feature branch, §3.4).
        branches.checkout_feature_branch(repo_root, slug)
        # Record cut-point (§3.7).
        cut_point = branches.record_cut_point(repo_root, slug)

        # Label transition: remove agent-ready, add agent-in-progress (C1).
        _label_edit(
            owner, repo, n, add=["agent-in-progress"], remove=["agent-ready"]
        )

        # Thread cut-point base to hooks via env (VP-1 wiring).
        os.environ["CHAIN_BASE_BRANCH"] = cut_point
        # Thread feature branch name to agent env so WORKFLOW.md step 4 can
        # use --base "$BH_FEATURE_BRANCH" in gh pr create (issue #67).
        os.environ["BH_FEATURE_BRANCH"] = branch_name

        # Fetch the Issue object.
        issue_obj = _fetch_issue_obj(owner, repo, n)
        if issue_obj is None:
            _log.error("daemon: could not fetch issue #%d; parking", n)
            _label_edit(owner, repo, n, remove=["agent-in-progress"])
            sched.mark_parked(n)
            parked_reasons[n] = "issue fetch failed"
            alert(
                owner,
                repo,
                n,
                f"Issue #{n} could not be fetched; worker not dispatched.",
                severity="warn",
                kind="debug",
                runlog=runlog,
            )
            continue

        # Dispatch the worker.
        # Emit dispatch event (best-effort; never raises into the loop).
        if runlog is not None:
            try:
                runlog.emit(
                    {
                        "ts": datetime.now(timezone.utc).isoformat(),
                        "event": "dispatch",
                        "issue": n,
                        "outcome": None,
                        "severity": "info",
                        "detail": f"dispatching worker for issue #{n}",
                        "tick_id": None,
                    }
                )
            except Exception:  # noqa: BLE001
                pass
        try:
            worker_result = await orch._run_worker(issue_obj)
        except Exception as exc:
            _log.error("daemon: _run_worker raised for #%d: %s", n, exc)
            _label_edit(owner, repo, n, remove=["agent-in-progress"])
            sched.mark_parked(n)
            parked_reasons[n] = f"worker exception: {exc}"
            alert(
                owner,
                repo,
                n,
                f"Issue #{n} worker raised an exception: {exc}",
                severity="warn",
                kind="debug",
                runlog=runlog,
            )
            continue

        # Emit outcome event (best-effort; never raises into the loop).
        if runlog is not None:
            try:
                runlog.emit(
                    {
                        "ts": datetime.now(timezone.utc).isoformat(),
                        "event": "outcome",
                        "issue": n,
                        "outcome": str(worker_result),
                        "severity": "info",
                        "detail": (
                            f"worker for issue #{n} returned {worker_result!r}"
                        ),
                        "tick_id": None,
                    }
                )
            except Exception:  # noqa: BLE001
                pass

        # Re-read labels after _run_worker (after_run may have set blocked).
        post_labels = _fetch_issue_labels(owner, repo, n)
        has_blocked = "blocked" in post_labels

        # Apply §3.5 outcome protocol.
        if worker_result == "pr_created" and not has_blocked:
            # CI gate.
            issue_branch, pr_head_sha = _find_issue_pr(owner, repo, n)
            if issue_branch is None or pr_head_sha is None:
                _log.warning(
                    "daemon: pr_created but no open PR found for #%d; parking",
                    n,
                )
                _label_edit(owner, repo, n, remove=["agent-in-progress"])
                sched.mark_parked(n)
                parked_reasons[n] = "pr_created but no PR located"
                alert(
                    owner,
                    repo,
                    n,
                    f"Issue #{n} returned pr_created but no PR found.",
                    severity="warn",
                    kind="debug",
                    runlog=runlog,
                )
                continue

            # FIX 2: wrap merge_issue_branch in a per-issue try/except so a
            # transient git/gh error parks this issue but does not kill the
            # daemon.
            try:
                outcome = merge_issue_branch(
                    repo_root=repo_root,
                    owner=owner,
                    repo=repo,
                    issue=n,
                    pr_head_sha=pr_head_sha,
                    issue_branch=issue_branch,
                    feature_branch=branch_name,
                    poll_interval=ci_poll_interval,
                    timeout=ci_timeout,
                )
            except Exception as exc:
                _log.error(
                    "daemon: merge_issue_branch raised for #%d: %s; parking",
                    n,
                    exc,
                )
                _label_edit(owner, repo, n, remove=["agent-in-progress"])
                sched.mark_parked(n)
                parked_reasons[n] = f"merge exception: {exc}"
                alert(
                    owner,
                    repo,
                    n,
                    f"Issue #{n} merge raised an exception: {exc}",
                    severity="warn",
                    kind="debug",
                    runlog=runlog,
                )
                continue

            if outcome == MergeOutcome.MERGED:
                # merge_issue_branch already added agent-merged + marker.
                _label_edit(
                    owner, repo, n, remove=["agent-in-progress", "agent-done"]
                )
                sched.mark_done(n)
                merged_issues.append(n)
                _log.info("daemon: issue #%d merged into %r", n, branch_name)
            else:
                _label_edit(owner, repo, n, remove=["agent-in-progress"])
                sched.mark_parked(n)
                parked_reasons[n] = f"CI gate: {outcome.name}"
                reason = (
                    "CI check failed"
                    if outcome == MergeOutcome.CI_FAILED
                    else "CI timed out"
                    if outcome == MergeOutcome.CI_TIMEOUT
                    else "merge conflict"
                )
                alert(
                    owner,
                    repo,
                    n,
                    f"Issue #{n} parked: {reason} ({outcome.name}).",
                    severity="critical",
                    kind="debug",
                    runlog=runlog,
                )
        else:
            # Park path: blocked or no_pr.
            kind = "block" if has_blocked else "debug"
            reason_text = (
                "blocked label set"
                if has_blocked
                else "no PR created (agent may have failed)"
            )
            _label_edit(owner, repo, n, remove=["agent-in-progress"])
            sched.mark_parked(n)
            parked_reasons[n] = reason_text
            alert(
                owner,
                repo,
                n,
                f"Issue #{n} parked: {reason_text}.",
                severity="warn",
                kind=kind,
                runlog=runlog,
            )

    # --- Step 3: completion. ---
    # Push the feature branch.
    push_proc = _run(
        ["git", "-C", str(repo_root), "push", "origin", branch_name]
    )
    if push_proc.returncode != 0:
        _log.warning(
            "daemon: git push %r failed (exit %d): %s",
            branch_name,
            push_proc.returncode,
            push_proc.stderr,
        )

    # Build PR body.
    # Each merged issue needs its own ``Closes #N`` keyword so GitHub
    # auto-closes all of them when the feature → main PR merges.  GitHub
    # does NOT parse comma-continuation (``closes #100, #101`` only closes
    # #100), so we emit one keyword per line (issue #67).
    if merged_issues:
        merged_section = "\n".join(f"Closes #{n}" for n in merged_issues)
    else:
        merged_section = "(none)"
    parked_list = (
        "\n".join(f"- #{n}: {reason}" for n, reason in parked_reasons.items())
        or "(none)"
    )
    pr_body = (
        f"## Work unit: {slug}\n\n"
        f"### Issues merged\n\n{merged_section}\n\n"
        f"### Issues parked (need human attention)\n\n{parked_list}\n"
        f"{_CLAUDE_ATTRIBUTION}"
    )
    pr_title = f"[daemon] {slug}"

    # Guard: skip _open_draft_pr when the feature branch has zero commits
    # over origin/main.  This prevents an empty "Warning: 1 uncommitted
    # change" PR when the agent produced no commits (issue #65).
    # Fail-open: if rev-list exits non-zero or stdout is unparseable, we
    # proceed to _open_draft_pr rather than silently losing the PR.
    count_proc = _run(
        [
            "git",
            "-C",
            str(repo_root),
            "rev-list",
            "--count",
            f"origin/main..{branch_name}",
        ]
    )
    if count_proc.returncode == 0 and count_proc.stdout.strip() == "0":
        _log.info(
            "daemon: work unit %r produced no commits over main"
            " — skipping draft PR (%d merged, %d parked)",
            slug,
            len(merged_issues),
            len(parked_reasons),
        )
    else:
        _open_draft_pr(owner, repo, branch_name, pr_title, pr_body)


# ---------------------------------------------------------------------------
# Outer daemon loop
# ---------------------------------------------------------------------------


async def run_daemon(
    config: WorkflowConfig,
    registry: list[RepoConfig],
    *,
    once: bool = False,
    poll_interval_s: float | None = None,
    ci_poll_interval: float = _DEFAULT_CI_POLL_INTERVAL,
    ci_timeout: float = _DEFAULT_CI_TIMEOUT,
) -> None:
    """Run the always-on serial daemon outer loop.

    Polls the registry for ready work units and processes them one at a
    time (B-I3 serial).  Never exits on a block.

    Args:
        config: The loaded ``WorkflowConfig``.
        registry: The list of ``RepoConfig`` entries (one entry in v1).
        once: If ``True``, run exactly one tick then return (for tests
            and the ``--once`` CLI flag).
        poll_interval_s: Seconds to sleep between outer-loop ticks.
            Defaults to ``config.poll_interval_ms / 1000``.
        ci_poll_interval: Seconds between CI polls in the merge gate.
        ci_timeout: Hard ceiling for the CI gate in seconds.
    """
    if poll_interval_s is None:
        poll_interval_s = config.poll_interval_ms / 1000

    _log.info(
        "daemon: starting (poll_interval=%.1fs, once=%s)",
        poll_interval_s,
        once,
    )

    # --- Observability startup (best-effort; risk R2 — must never raise). ---
    runlog: RunLog | None = None
    try:
        obs = load_obs_config()
        runlog = RunLog(obs.runlog_path)
        runlog.emit(
            {
                "ts": datetime.now(timezone.utc).isoformat(),
                "event": "daemon_start",
                "issue": None,
                "outcome": None,
                "severity": "info",
                "detail": "daemon starting up",
                "tick_id": None,
            }
        )
    except Exception as exc:  # noqa: BLE001
        _log.warning("daemon: observability init failed: %s", exc)
        runlog = None

    while True:
        for repo_cfg in registry:
            # FIX 2: defensive catch around each per-repo tick.  A failure
            # building or running one work unit must not kill the always-on
            # daemon.  Log, escalate if possible, then continue to the next
            # repo/tick.
            try:
                await _poll_and_run(
                    config,
                    repo_cfg,
                    ci_poll_interval=ci_poll_interval,
                    ci_timeout=ci_timeout,
                    runlog=runlog,
                )
            except Exception as exc:
                _log.error(
                    "daemon: unhandled exception for %s/%s: %s; "
                    "daemon continues",
                    repo_cfg.owner,
                    repo_cfg.repo,
                    exc,
                )
                try:
                    alert(
                        repo_cfg.owner,
                        repo_cfg.repo,
                        None,
                        f"Daemon tick failed for {repo_cfg.owner}/"
                        f"{repo_cfg.repo}: {exc}",
                        severity="critical",
                        kind="debug",
                        runlog=runlog,
                    )
                except Exception:
                    pass  # escalation itself may fail; daemon must survive

        if once:
            break

        await asyncio.sleep(poll_interval_s)

    _log.info("daemon: stopped")


async def _poll_and_run(
    config: WorkflowConfig,
    repo_cfg: RepoConfig,
    *,
    ci_poll_interval: float,
    ci_timeout: float,
    runlog: RunLog | None = None,
) -> None:
    """Poll one repo for a ready work unit and run it if found.

    Args:
        config: The loaded ``WorkflowConfig``.
        repo_cfg: The repo registry entry.
        ci_poll_interval: Seconds between CI polls.
        ci_timeout: Hard CI ceiling in seconds.
        runlog: Optional ``RunLog`` handle for best-effort event
            emission.  When ``None``, all emission is a no-op.
    """
    owner = repo_cfg.owner
    repo = repo_cfg.repo

    # Fetch open agent-ready issues.
    proc = _run(
        [
            "gh",
            "issue",
            "list",
            "--repo",
            f"{owner}/{repo}",
            "--label",
            "agent-ready",
            "--state",
            "open",
            "--json",
            "number,title,state,body,url,labels,milestone,assignees",
            "--limit",
            "100",
        ]
    )
    if proc.returncode != 0:
        _log.error(
            "daemon: gh issue list failed (exit %d): %s",
            proc.returncode,
            proc.stderr,
        )
        return

    try:
        issues_raw = json.loads(proc.stdout)
    except (json.JSONDecodeError, TypeError) as exc:
        _log.error("daemon: issue list parse error: %s", exc)
        return

    # Filter out issues that also have "blocked" label.
    ready_issues = [
        i
        for i in issues_raw
        if "blocked"
        not in {lbl["name"].lower() for lbl in i.get("labels", [])}
    ]

    if not ready_issues:
        _log.debug("daemon: no ready issues in %s/%s", owner, repo)
        return

    # Select ONE ready work unit (B-I3 serial).
    # Priority: milestoned first; then un-milestoned by number.
    work_unit = _select_work_unit(ready_issues)
    if work_unit is None:
        return

    branch_name, slug, membership, milestone_info = work_unit

    # FIX 1: Expand membership to ALL open milestone members so that
    # build_dag sees blocker edges from non-ready members.  An agent-ready
    # subset as membership silently drops A→B edges where A is not yet
    # greenlit, causing B to be dispatched out of dependency order.
    if milestone_info is not None:
        ms_num, ms_title = milestone_info
        full_members = _fetch_full_milestone_members(
            owner, repo, ms_num, ms_title
        )
        if full_members:
            membership = full_members

    await _run_work_unit(
        config=config,
        repo_cfg=repo_cfg,
        branch_name=branch_name,
        slug=slug,
        membership=membership,
        agent_ready_issues=frozenset(i["number"] for i in ready_issues),
        ci_poll_interval=ci_poll_interval,
        ci_timeout=ci_timeout,
        runlog=runlog,
    )


def _select_work_unit(
    issues: list[dict[str, Any]],
) -> tuple[str, str, frozenset[int], tuple[int, str] | None] | None:
    """Select exactly one ready work unit from the list of ready issues.

    A milestoned issue represents a milestone work unit (all members of
    that milestone form the unit).  An un-milestoned issue is its own
    N=1 unit.

    Selection priority: milestone units first (lowest milestone number),
    then un-milestoned by issue number.

    Args:
        issues: List of raw issue dicts from the ``gh issue list`` output.

    Returns:
        A ``(branch_name, slug, membership, milestone_info)`` tuple or
        ``None`` if no work unit can be determined.  ``milestone_info`` is
        a ``(milestone_number, milestone_title)`` pair for milestone work
        units, or ``None`` for un-milestoned single-issue units.  The
        caller uses ``milestone_info`` to expand ``membership`` to the full
        set of open milestone issues (FIX 1).
    """
    # Prefer milestoned issues first.
    milestoned = [i for i in issues if i.get("milestone")]
    if milestoned:
        # Pick the milestone with the lowest number.
        milestone = min(
            (i["milestone"] for i in milestoned),
            key=lambda m: m.get("number", 0),
        )
        ms_num = milestone["number"]
        ms_title = milestone.get("title", f"milestone-{ms_num}")
        ms_slug = _slugify(ms_title)
        branch_name = f"feature/{ms_slug}"
        slug = ms_slug
        # Initial membership from the agent-ready subset only.
        # _poll_and_run expands this to the full open milestone set via
        # _fetch_full_milestone_members (FIX 1).
        members = frozenset(
            i["number"]
            for i in milestoned
            if i.get("milestone", {}).get("number") == milestone["number"]
        )
        return branch_name, slug, members, (ms_num, ms_title)

    # Un-milestoned: pick the lowest issue number.
    un_milestoned = sorted(
        [i for i in issues if not i.get("milestone")],
        key=lambda i: i["number"],
    )
    if un_milestoned:
        n = un_milestoned[0]["number"]
        from baton_harness.chain.branches import feature_branch_name

        branch_name = feature_branch_name(issue=n)
        slug = f"issue-{n}"
        return branch_name, slug, frozenset({n}), None

    return None
